version: "3.5"


services:
#---- database layer
  pgdb:
    image: "postgres:12"
#    restart: "always"
    ports:
      - "5432:5432"
    env_file:
      - "variables.env"
    volumes:
      - "./postgresdata:/var/lib/postgresql/data"


