# Generated by Django 3.1.2 on 2020-10-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadrivenapp', '0003_remove_fromengas_branchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fromengas',
            name='TRANSACTION_NO',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
